### ISSUE TITLE
Something really strange happend when developer tools is open.

### ISSUE THREAD

**Issue by eduinlight** [inflagames/azetz#44]
![Screenshot from 2021-08-28 04-39-48](https://user-images.githubusercontent.com/32907001/131202326-240c225d-34da-429e-ad04-b01b52ba8f23.png)

**Comment by wil92** [comment]
are you using firefox? because I do not have problems with chrome

**Comment by eduinlight** [comment]
No, I always use chrome version 92 now.

**Comment by wil92** [comment]
Is this still happening
