### ISSUE TITLE
Proposition to change ship control behaviour

### ISSUE THREAD

**Issue by eduinlight** [inflagames/azetz#45]
Rather than touch the ship to make it move. Whay do not change this behaviour and with touch take the position and with the angle and move it in that direction. This has one problem and question. Then,  how we handle the velocity? Maybe if we use an adition button (low right with a propulsion simbol). The idea es with one finger I set the velocity and with the other the angle to move. I think that is is better for user experience that what we have now. Tell me your thoughts.

**Comment by wil92** [comment]
make sense, less split the questions and talk about them
- Hot to handler velocity? this is not implemented yet, the velocity is always the same. I think we can define it by the distance of the mouse from the ship.
- change the click over the ship to flight? I'm ok with it, but I think we should change it, depending on the device, if we are in a computer, we should by default show the line that defines the direction to flight of the ship, but if we are in a mobile, then we should show the line when the user touch the screen and move the ship at the moment the user releases the finger from the scree. What do you think about it?

**Comment by eduinlight** [comment]
**How to handler velocity? this is not implemented yet, the velocity is always the same. I think we can define it by the distance of the mouse from the ship.** I thought that velocity is important here. That's why I think in this proposition.
**change the click over the ship to flight? I'm ok with it, but I think we should change it, depending on the device, if we are in a computer, we should by default show the line that defines the direction to flight of the ship, but if we are in a mobile, then we should show the line when the user touch the screen and move the ship at the moment the user releases the finger from the scree. What do you think about it?**  AGREE

**Comment by wil92** [comment]
**How to handler velocity?**
yeap, should be, but right now we have a fixed velocity
